/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ucr.ac.cr.tm2100.g3.juegopila.view;

import java.awt.Graphics;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.Timer;
import ucr.ac.cr.tm2100.g3.juegopila.controller.Controller;
import ucr.ac.cr.tm2100.g3.juegopila.model.Enemigo;
import ucr.ac.cr.tm2100.g3.juegopila.model.Jugador;
import ucr.ac.cr.tm2100.g3.juegopila.model.Matriz;

/**
 *
 * @author bombe
 */
public class PanelTablero extends javax.swing.JPanel {

    private Jugador jugador;
    private Random random = new Random();
    private Timer temporizador;
    private Matriz mapa;
    private ImageIcon personaje;
    private int matriz[][];

    /**
     * Creates new form PanelTablero
     */
    public PanelTablero() {
        initComponents();
        this.mapa = new Matriz();
        jugador = new Jugador(43, 36, mapa.getMatriz());

        setFocusable(true);
        requestFocusInWindow();

        addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyPressed(java.awt.event.KeyEvent e) {
                int dx = 0, dy = 0;
                switch (e.getKeyCode()) {
                    case java.awt.event.KeyEvent.VK_W:
                        dy = -20;
                        System.out.println("Se ha movido Arriba");
                        personaje = new ImageIcon("./src/main/resources/img/JugadorUp.png");
                        jugador.setIcono(personaje);
                        break;
                    case java.awt.event.KeyEvent.VK_S:
                        dy = 20;
                        System.out.println("Se ha movido Abajo");
                        personaje = new ImageIcon("./src/main/resources/img/JugadorDown.png");
                        jugador.setIcono(personaje);
                        break;
                    case java.awt.event.KeyEvent.VK_A:
                        dx = -20;
                        System.out.println("Se ha movido Izquierda");
                        personaje = new ImageIcon("./src/main/resources/img/JugadorLeft.png");
                        jugador.setIcono(personaje);
                        break;
                    case java.awt.event.KeyEvent.VK_D:
                        dx = 20;
                        System.out.println("Se ha movido Derecha");
                        personaje = new ImageIcon("./src/main/resources/img/JugadorRigth.png");
                        jugador.setIcono(personaje);
                        break;
                }
                jugador.mover(dx, dy); // Actualiza la posición del jugador
                repaint(); // Vuelve a dibujar el panel con la nueva posición
            }
        });
    }

    public void setControlador(Controller controlador) {
        addMouseListener(controlador);

    }

    public void paint(Graphics g) {
        super.paint(g);
        jugador.dibujar(g);
    }

    //metodo para controlar los movimientos del jugador 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JLabel();

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Mapa2Juego.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fondo)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondo;
    // End of variables declaration//GEN-END:variables
}
