/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ucr.ac.cr.tm2100.g3.juegopila.view;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author bombe
 */
public class PanelForInstrucctions extends javax.swing.JPanel {
    
    private ImageIcon instrucciones;
    /**
     * Creates new form PanelForInstrucctions
     */
    public PanelForInstrucctions() {
        initComponents();
        instrucciones=new ImageIcon("./src/main/resources/img/Instrucciones.png");
        Image fondoI=instrucciones.getImage().getScaledInstance(1540, 800, 100);
    }
    
    public int getAncho(){
        return instrucciones.getIconWidth();
    }
    
    public int getAlto(){
        return instrucciones.getIconHeight();
    }
    
    public void paint(Graphics g)/*g es el objeto grafico*/{
        super.paint(g);//siempre en la primer linea del metodo
        instrucciones.paintIcon(null, g, 0, 0);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
